### ISSUE TITLE
Not able to properly upload large files

### ISSUE THREAD

**Issue by alinpopa** [jpscaletti/tus#5]
I'm trying to upload a ~ 750 MB size file, using a very very basic Phoenix controller based on the description, nothing too special, and not able to properly upload a large file.
I've used an existing project, just to make sure I'm not missing anything: https://github.com/jpscaletti/tus-demo and also, for the client, this code: https://github.com/tus/tus-js-client
On the server side I'm able to see messages like this:
```
[info] POST /files/
[debug] Processing with DemoWeb.UploadController.post/2
  Parameters: %{}
  Pipelines: []
on_begin_upload
%Tus.File{
  created_at: 1533642291,
  metadata: [{"filename", "mydb.dump"}],
  metadata_src: "filename bXlkYi5kdW1w",
  offset: 0,
  parts: [],
  path: "2018/8/7/4b36a914-9a37-11e8-9106-060064394d01",
  size: 784027165,
  uid: "4b36a914-9a37-11e8-9106-060064394d01",
  upload_id: nil
}
------
[info] Sent 201 in 1ms
[info] PATCH /files/4b36a914-9a37-11e8-9106-060064394d01
[debug] Processing with DemoWeb.UploadController.patch/2
  Parameters: %{"uid" => "4b36a914-9a37-11e8-9106-060064394d01"}
  Pipelines: []
[info] Sent 204 in 30ms
[info] PATCH /files/4b36a914-9a37-11e8-9106-060064394d01
[debug] Processing with DemoWeb.UploadController.patch/2
  Parameters: %{"uid" => "4b36a914-9a37-11e8-9106-060064394d01"}
  Pipelines: []
[info] HEAD /files/4b36a914-9a37-11e8-9106-060064394d01
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /files/4b36a914-9a37-11e8-9106-060064394d01 (DemoWeb.Router)
    (demo) lib/demo_web/router.ex:1: DemoWeb.Router.__match_route__/4
    (demo) lib/phoenix/router.ex:303: DemoWeb.Router.call/2
    (demo) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.plug_builder_call/2
    (demo) lib/plug/debugger.ex:102: DemoWeb.Endpoint."call (overridable 3)"/2
    (demo) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4

[info] POST /files/
[debug] Processing with DemoWeb.UploadController.post/2
  Parameters: %{}
  Pipelines: []
on_begin_upload
%Tus.File{
  created_at: 1533642291,
  metadata: [{"filename", "mydb.dump"}],
  metadata_src: "filename bXlkYi5kdW1w",
  offset: 0,
  parts: [],
  path: "2018/8/7/4b425e3a-9a37-11e8-822d-060064394d01",
  size: 784027165,
  uid: "4b425e3a-9a37-11e8-822d-060064394d01",
  upload_id: nil
}
------
[info] Sent 201 in 1ms
[info] Sent 204 in 39ms
[info] PATCH /files/4b425e3a-9a37-11e8-822d-060064394d01
[debug] Processing with DemoWeb.UploadController.patch/2
  Parameters: %{"uid" => "4b425e3a-9a37-11e8-822d-060064394d01"}
  Pipelines: []
[info] Sent 204 in 30ms
[info] HEAD /files/4b425e3a-9a37-11e8-822d-060064394d01
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /files/4b425e3a-9a37-11e8-822d-060064394d01 (DemoWeb.Router)
    (demo) lib/demo_web/router.ex:1: DemoWeb.Router.__match_route__/4
    (demo) lib/phoenix/router.ex:303: DemoWeb.Router.call/2
    (demo) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.plug_builder_call/2
    (demo) lib/plug/debugger.ex:102: DemoWeb.Endpoint."call (overridable 3)"/2
    (demo) lib/demo_web/endpoint.ex:1: DemoWeb.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:16: Plug.Adapters.Cowboy.Handler.upgrade/4
```
but the GET call (which I wasn't able to find it documented as part of the TUS protocol) is worrying in particular.

On the client side, these are the messages I'm seeing:
```
65536 784027165 '0.01%'
8000000 784027165 '1.02%'
8065536 784027165 '1.03%'
65536 784027165 '0.01%'
Failed because: Error: tus: failed to upload chunk at offset 0, caused by Error: write EPIPE, originated from request (response code: 0, response text: )
65536 784027165 '0.01%'
65536 784027165 '0.01%'
65536 784027165 '0.01%'
Failed because: Error: tus: failed to upload chunk at offset 0, caused by Error: write EPIPE, originated from request (response code: 0, response text: )
```

Could anyone, please, tell me if I'm missing something in my setup?
Thanks, Alin.

**Comment by alinpopa** [comment]
Looks like there is a problem that got fixed within Cowboy 2: https://github.com/ninenines/cowboy/commit/763eef4e46dd8ffb5bb10ddccb1eb761971d8382
Managed to make this work by copying this code, and placing it within a simple plug application, that uses the master version of Cowboy 2, and everything seems to be working fine.
